###################################################################

# Created by write_sdc on Thu May  7 03:09:49 2026

###################################################################
set sdc_version 2.0

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_fanout_load 8 [get_ports {S[7]}]
set_fanout_load 8 [get_ports {S[6]}]
set_fanout_load 8 [get_ports {S[5]}]
set_fanout_load 8 [get_ports {S[4]}]
set_fanout_load 8 [get_ports {S[3]}]
set_fanout_load 8 [get_ports {S[2]}]
set_fanout_load 8 [get_ports {S[1]}]
set_fanout_load 8 [get_ports {S[0]}]
set_fanout_load 8 [get_ports Co]
create_clock [get_ports clk]  -period 0.4  -waveform {0 0.2}
set_input_delay -clock clk  -max 0.01  [get_ports clk]
set_input_delay -clock clk  -min 0  [get_ports clk]
set_input_delay -clock clk  -max 0.01  [get_ports rst]
set_input_delay -clock clk  -min 0  [get_ports rst]
set_input_delay -clock clk  -max 0.01  [get_ports Ci]
set_input_delay -clock clk  -min 0  [get_ports Ci]
set_input_delay -clock clk  -max 0.01  [get_ports {A[7]}]
set_input_delay -clock clk  -min 0  [get_ports {A[7]}]
set_input_delay -clock clk  -max 0.01  [get_ports {A[6]}]
set_input_delay -clock clk  -min 0  [get_ports {A[6]}]
set_input_delay -clock clk  -max 0.01  [get_ports {A[5]}]
set_input_delay -clock clk  -min 0  [get_ports {A[5]}]
set_input_delay -clock clk  -max 0.01  [get_ports {A[4]}]
set_input_delay -clock clk  -min 0  [get_ports {A[4]}]
set_input_delay -clock clk  -max 0.01  [get_ports {A[3]}]
set_input_delay -clock clk  -min 0  [get_ports {A[3]}]
set_input_delay -clock clk  -max 0.01  [get_ports {A[2]}]
set_input_delay -clock clk  -min 0  [get_ports {A[2]}]
set_input_delay -clock clk  -max 0.01  [get_ports {A[1]}]
set_input_delay -clock clk  -min 0  [get_ports {A[1]}]
set_input_delay -clock clk  -max 0.01  [get_ports {A[0]}]
set_input_delay -clock clk  -min 0  [get_ports {A[0]}]
set_input_delay -clock clk  -max 0.01  [get_ports {B[7]}]
set_input_delay -clock clk  -min 0  [get_ports {B[7]}]
set_input_delay -clock clk  -max 0.01  [get_ports {B[6]}]
set_input_delay -clock clk  -min 0  [get_ports {B[6]}]
set_input_delay -clock clk  -max 0.01  [get_ports {B[5]}]
set_input_delay -clock clk  -min 0  [get_ports {B[5]}]
set_input_delay -clock clk  -max 0.01  [get_ports {B[4]}]
set_input_delay -clock clk  -min 0  [get_ports {B[4]}]
set_input_delay -clock clk  -max 0.01  [get_ports {B[3]}]
set_input_delay -clock clk  -min 0  [get_ports {B[3]}]
set_input_delay -clock clk  -max 0.01  [get_ports {B[2]}]
set_input_delay -clock clk  -min 0  [get_ports {B[2]}]
set_input_delay -clock clk  -max 0.01  [get_ports {B[1]}]
set_input_delay -clock clk  -min 0  [get_ports {B[1]}]
set_input_delay -clock clk  -max 0.01  [get_ports {B[0]}]
set_input_delay -clock clk  -min 0  [get_ports {B[0]}]
set_output_delay -clock clk  -max 0.01  [get_ports {S[7]}]
set_output_delay -clock clk  -min 0  [get_ports {S[7]}]
set_output_delay -clock clk  -max 0.01  [get_ports {S[6]}]
set_output_delay -clock clk  -min 0  [get_ports {S[6]}]
set_output_delay -clock clk  -max 0.01  [get_ports {S[5]}]
set_output_delay -clock clk  -min 0  [get_ports {S[5]}]
set_output_delay -clock clk  -max 0.01  [get_ports {S[4]}]
set_output_delay -clock clk  -min 0  [get_ports {S[4]}]
set_output_delay -clock clk  -max 0.01  [get_ports {S[3]}]
set_output_delay -clock clk  -min 0  [get_ports {S[3]}]
set_output_delay -clock clk  -max 0.01  [get_ports {S[2]}]
set_output_delay -clock clk  -min 0  [get_ports {S[2]}]
set_output_delay -clock clk  -max 0.01  [get_ports {S[1]}]
set_output_delay -clock clk  -min 0  [get_ports {S[1]}]
set_output_delay -clock clk  -max 0.01  [get_ports {S[0]}]
set_output_delay -clock clk  -min 0  [get_ports {S[0]}]
set_output_delay -clock clk  -max 0.01  [get_ports Co]
set_output_delay -clock clk  -min 0  [get_ports Co]
